apiVersion: napptive.com/v1
kind: Catalog
metadata:
  name: appwrite-catalog
  displayName: Appwrite Catalog
spec:
  description: Catalog for deploying Appwrite server
  items:
    - name: appwrite-server
      displayName: Appwrite Server
      description: "Appwrite is a self-hosted backend server for web and mobile applications."
      iconUrl: "https://example.com/appwrite-logo.png"
      versions:
        - version: 1.3.1
          description: "Version 1.3.1 of Appwrite server"
          containers:
            - image: appwrite/appwrite:1.3.1
              name: appwrite-container
              environment:
                - name: APPWRITE_API_KEY
                  value: ""
                - name: APPWRITE_PROJECT_ID
                  value: ""
              ports:
                - containerPort: 80
                  protocol: TCP
